### ISSUE TITLE
Problem with notes visibility feature

### ISSUE THREAD

**Issue by jfavellar90** [openedx/frontend-app-learning#1005]
This issue is related to the BTR issue https://github.com/openedx/build-test-release-wg/issues/227 in the context of the Nutmeg release work. The testing of the cases was performed in the [BTR Olive instance](https://github.com/overhangio/openedx-release-demo).

There's a problem due to a discrepancy between the management of the notes visibility in the MFE and the Iframe serving an xblock unit content.

The notes visibility is meant to be controlled by a **student preference** called **"edxnotes_visibility"**, which is stored in the table **courseware_xmodulestudentinfofield**. If the preference is not present for the currently logged-in user, the notes visibility is enabled by default. The unit content in a courseware page is loaded through an [Iframe](https://github.com/openedx/frontend-app-learning/blob/open-release/olive.master/src/courseware/course/sequence/Unit.jsx#L218) inside the MFE, and the preference value determines if the notes are highlighted or not when the unit is loaded.

However, the MFE notes visibility ignores the aforementioned user preference and determines the visibility based on the course metadata info extracted from a [courseware API call](https://github.com/openedx/frontend-app-learning/blob/open-release/olive.master/src/courseware/data/api.js#L128). This API returns the values for notes in the format below:

```
notes:
  enabled: true
  visible: true
```

And this API always returns the `visible` field with a `true` value, not taking into account the "edxnotes_visibility" preference of the user. This affects the behavior of the [button](https://github.com/openedx/frontend-app-learning/blob/open-release/olive.master/src/courseware/course/content-tools/notes-visibility/NotesVisibility.jsx#L28-L32) that toggles the notes visibility, due to the discrepancy between the notes visibility state of the unit Iframe and the MFE.

The notes visibility value in the MFE should be extracted from another source to get the value of the user preference (or make the courseware API in the LMS aware of the user calling it?).

**Comment by Agrendalath** [comment]
Fixed in https://github.com/openedx/edx-platform/pull/33096 and https://github.com/openedx/frontend-app-learning/pull/1170.
