### ISSUE TITLE
Upgrade React JS to v17

### ISSUE THREAD

**Issue by abdullahwaheed** [openedx/frontend-app-learning#1133]
This repo is currently using React JS v16. We need to upgrade it to React 17 before moving to latest React version(v18).
React 17 doesn’t add any new developer-facing features, so its upgrade might not cause any breaking changes. Our end goal is to upgrade React to v18 but v18 no longer support enzyme, so we are upgrading to React 17 and then we’ll migrate from enzyme.

### Epic Link ###
[React 17 upgrade](https://github.com/openedx/platform-roadmap/issues/277)

**Comment by jmbowman** [comment]
It looks like the PR for this was merged, is this done now?
