### ISSUE TITLE
Untranslatable strings 

### ISSUE THREAD

**Issue by ghassanmas** [openedx/frontend-app-learning#1193]
The Following is a list of strings that are hardcoded, untranslatable 

 1.   `View course in` https://github.com/openedx/frontend-app-learning/blob/168ed1e184ccafa6e36e044d6e95429936672b9b/src/instructor-toolbar/InstructorToolbar.jsx#L78
 2. `Specific Student... ` https://github.com/openedx/frontend-app-learning/blob/168ed1e184ccafa6e36e044d6e95429936672b9b/src/instructor-toolbar/masquerade-widget/MasqueradeWidget.jsx#L99
 3. `View this course as:` https://github.com/openedx/frontend-app-learning/blob/168ed1e184ccafa6e36e044d6e95429936672b9b/src/instructor-toolbar/masquerade-widget/MasqueradeWidget.jsx#L123

**Comment by jciasenza** [comment]
I can take this issue @arbrandes

**Comment by jciasenza** [comment]
@arbrandes 
Add message ids and add a file
src/instructor-toolbar/messages.js
![image](https://github.com/user-attachments/assets/b41a51a7-55ba-439d-ad33-33c95185cdca)

Also modify the masquerade
src/instructor-toolbar/masquerade-widget/MasqueradeWidget.jsx
![image](https://github.com/user-attachments/assets/357cb7eb-b997-476b-a841-4d156ae9a129)

If you approve my changes I will push them,
or if something needs to be modified let me know thanks !!!
Atte 
Juan Carlos (Aulasneo)
