### ISSUE TITLE
`PUBLIC_PATH` support is not working anymore after react router v6 upgrade

### ISSUE THREAD

**Issue by arslanashraf7** [openedx/frontend-app-learning#1207]
### Context:

In the past, The learning MFE used to support subdirectory paths i.e. `PUBLIC_PATH`. This helps the deployment of learning MFE in subdirectories and accessing it through an exposed `PUBLIC_PATH`.

### Example

Suppose we have a use case where we want to access Learning MFE from a subdirectory on a path e.g. `/learn` instead of `/`. To do this in the past, we would add a config variable i.e. `PUBLIC_PATH='/learn/'` in `.env.development` (In case of local instance). Once done the learning MFE can be accessed at `localhost:2000/learn/course/...`.

### Issue

It looks like after [feat: upgrade react router to v6](https://github.com/openedx/frontend-app-learning/pull/1128) the `PUBLIC_PATH` is not working anymore. This could probably be because of some missing configurations in the new ReactRouter version (`v6`) to support this. 

OR

A possible solution is that we have defined routes like [  HOME: '/course/:courseId/home',](https://github.com/openedx/frontend-app-learning/blob/master/src/constants.js#L3) Which would not care if there is any `PUBLIC_PATH` defined. We should probably refactor these to use the `PUBLIC_PATH`. A reference for how this can be done can be seen in **[Discussions MFE](https://github.com/openedx/frontend-app-discussions/blob/68c18526fbfb34f95c967c19bfee0ad07d4f0c75/src/data/constants.js#L140)**.

**Comment by arbrandes** [comment]
This was fixed in master by https://github.com/openedx/frontend-app-learning/pull/1209.  What we're missing now is a backport.

**Comment by arslanashraf7** [comment]
> This was fixed in master by #1209. What we're missing now is a backport.

Great. @arbrandes Thanks!

**Comment by arbrandes** [comment]
This is the backport, for the record: https://github.com/openedx/frontend-app-learning/pull/1210

**Comment by arbrandes** [comment]
Looks like we've been done here for a while! :)
