### ISSUE TITLE
Issues with '@edx/frontend-platform/auth'

### ISSUE THREAD

**Issue by S1mpleOW** [openedx/frontend-app-learning#1293]
I am trying to develop a custom MFE with MFE template. I have configured the environment variables following the documentation. However, after running npm start, I have an error message with REFRESH_ACCESS_TOKEN_ENDPOINT when get authenticated and fetch authenticated user. Can anyone help me resolve this issue. I appreciate this a lot!

**Comment by bradenmacdonald** [comment]
Hi @S1mpleOW. If you are still having issues with MFE development, please make a post on [the forum](https://discuss.openedx.org/) or on Slack and we can help you there. If you're developing a custom MFE, it's not really related to this GitHub repo.
