### ISSUE TITLE
Bug: Left-sidebar navigation - Sections and subsections being marked as complete when not all units completed

### ISSUE THREAD

**Issue by crathbun428** [openedx/frontend-app-learning#1385]
1. Steps to Reproduce
- When I have the left-sidebar navigation enabled on my instance and I navigate to an in-course experience page

3. Expected Result
- Then I see that the sections/subsections with all subsections/units completed show a completion checkmark

5. Actual Result
- I sometimes (see note) see the completion check mark next to every section and subsection even for sections/subsections containing incomplete units

Note: 
- I am not certain exactly what I did that triggered this behavior. I was testing the left-sidebar navigation, I clicked the progress tab, and went back into the course and saw this behavior. I went back to the dashboard, selected the course I was testing, clicked resume course and saw the behavior went away, went back to the course outline and clicked a course unit in the outline and the behavior returned. Now I can't seem to get it back to normal. 
![Screenshot 2024-05-08 at 4 36 17 PM](https://github.com/openedx/frontend-app-course-authoring/assets/57507106/27ebc6eb-f04a-4454-9a1e-e0de8f75ce4b)

**Comment by mariajgrimaldi** [comment]
FYI @arbrandes @brian-smith-tcril @openedx/2u-aurora, please tag anyone who can help.

**Comment by GlugovGrGlib** [comment]
@crathbun428 @mariajgrimaldi This should be fixed by https://github.com/openedx/frontend-app-learning/pull/1398, it was merged today

**Comment by mariajgrimaldi** [comment]
@GlugovGrGlib: great! Could you folks help us with the backport? We'd appreciate it.

EDIT: I see that's actually the backport. I'm sorry 😅

**Comment by mariajgrimaldi** [comment]
This worked for me in the Redwood sandbox. Please, @crathbun428 feel free to close the issue once you confirm it was fixed. Thanks!

**Comment by crathbun428** [comment]
@mariajgrimaldi - Confirmed! I see that this behavior no longer occurs when I take the steps I mention in the example. I will close this issue now.
