### ISSUE TITLE
After resetting I can submit again without selecting a new option and it uses the previous submit value

### ISSUE THREAD

**Issue by mariajgrimaldi** [openedx/frontend-app-learning#1406]
### Expected behavior

The "Submit" button should be disabled after clicking reset option. 

### Actual behavior

After clicking the "Reset" button, questions are reset, but the "Submit" button stays active and clickable. If the user clicks the "Submit" button without selecting any option, it is marked incorrect.

https://github.com/openedx/wg-build-test-release/assets/170630433/7f84c701-2a97-44e4-9486-2e32d13fa298

### Steps to reproduce

1. Navigate to a common problem type component (SCQ, MCQ ) in the course.
2. Attempt a question and submit an incorrect answer.
3. Click the "Reset" button to reset the question.
4. Click the submit button without selecting any option.
5. Observe the behavior. 

### Additional information

1. This issue affects all common problem components.

Original issue: https://github.com/openedx/edx-platform/issues/36824

**Comment by mariajgrimaldi** [comment]
This is currently happening in quince as well.

**Comment by mariajgrimaldi** [comment]
FYI @arbrandes @brian-smith-tcril @openedx/2u-infinity, please tag anyone you think can help. Thanks!

**Comment by imasdekar** [comment]
@mariajgrimaldi  I have sent a merge request: https://github.com/openedx/edx-platform/pull/35118 to fix this issue. Please take a look

**Comment by mariajgrimaldi** [comment]
Hey @imasdekar, thank you so much for the fix! We really appreciate it. I'll look (or find someone who can) as soon as possible.

**Comment by mariajgrimaldi** [comment]
This issue affects edx-platform instead of the MFE, so I'm going to close the issue in the MFE to track it in the BTR repo directly.
