### ISSUE TITLE
Left sidebar navigation breaks rendering of course

### ISSUE THREAD

**Issue by KristinAoki** [openedx/frontend-app-learning#1437]
On the edX production site, the enabling of the left sidebar navigation prevents the page from rendering. When looking at the Network tab in Dev tools, the navigation API, `/api/course_home/v1/navigation/undefined` returns 404 because the course id is undefined. It should be noted that this does not occur on all the edX environments.

Screen recording of the behavior:
<video src="https://github.com/user-attachments/assets/f137433c-cb32-4325-a063-518d429e6eca" />

Screenshot of console errors
<img width="550" alt="Screenshot 2024-08-14 at 1 29 45 PM" src="https://github.com/user-attachments/assets/08de92d9-4e93-48b1-b294-ec6711b5ce3c">

The error points to the `useEffect` in `src/courseware/course/sidebar/sidebars/course-outline/hooks.jsx`

Reproduction steps

1. Enable `courseware.enable_navigation_sidebar` waffle flag
2. Open a course
3. See the spinner for loading the course content
4. Shown unexpected error occurred message

**Comment by qasimgulzar** [comment]
@KristinAoki could you please add steps to reproduce.
