### ISSUE TITLE
with what backend version this microfrontend should work?

### ISSUE THREAD

**Issue by mohaalak** [openedx/frontend-app-learning#69]
the API call to 
```
/api/courses/v2/blocks/?course_id={course_id}
```
and 
```
/api/courseware/course/{course_id}
```

will return 404 and I did not find these URL routes in [EDX platform GitHub repo](https://github.com/edx/edx-platform)

can you help me out? I'm so confused

@edx/teaching-and-learning

**Comment by bradenmacdonald** [comment]
Closing as this is an old question. In general the `master` branch of this repo should work with the `master` branch of edx-platform, and similar for named releases - the `openedx-release/redwood.master` branch of both this and edx-platform should work together.
