### ISSUE TITLE
Rewrite calculator supported constants 

### ISSUE THREAD

**Issue by ghassanmas** [openedx/frontend-app-learning#820]
So in calcualtor examples tables in list some constants that are no longer supported: 

https://github.com/openedx/frontend-app-learning/blob/61f0ce2023cc2332a1e1fe5dd3dae035074b6e46/src/courseware/course/content-tools/calculator/Calculator.jsx?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L257-L266 

In calcuator V3 some constants are removed, hence: https://github.com/openedx/openedx-calc/commit/5e75af6ce444ce4933ef145bb4f57d64eaeb6433 

Also this might lead to [affiex tip](https://github.com/openedx/frontend-app-learning/blob/61f0ce2023cc2332a1e1fe5dd3dae035074b6e46/src/courseware/course/content-tools/calculator/Calculator.jsx?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L140-L145) to not work as expected, so may be this also need to be removed:

**Comment by pdpinch** [comment]
Thanks for bringing this to my attention @ghassanmas. I was able to find the original PR that removed some of the constants, at https://github.com/openedx/edx-platform/pull/17368

The constants `k`, `c`, `T`, and `q` were all causing user confusion and leading to unnecessary forum posts and support tickets. Support was removed, so they should also be removed from these examples.
